const GET_ALLDOGS = "GET_ALLDOGS"
const POST_DOG = "POST_DOG"
const SUCCESSFUL = "SUCCESSFUL"
const ERROR = "ERROR"
const TEMPERAMENTS = "TEMPERAMENTS"
const BY_SELECT = "FILTER_SELECT"
const ORDER_SELECT = "ORDER_SELECT"
const TEMPERAMENTS_SELECT = "TEMPERAMENTS_SELECT"
const NAME_SEARCH = "NAME_SEARCH"
const PAGE_NUMBER = "PAGE_NUMBER"
const AMOUNT_PAGES = "AMOUNT_PAGES"
const LOADING = "LOADING"
const SEARCH_ID = "SEARCH_ID"
const CLEAR_DETAIL_DOGS = "CLEAR_DETAIL_DOGS"
module.exports ={
    GET_ALLDOGS,
    POST_DOG,
    ERROR,
    SUCCESSFUL,
    TEMPERAMENTS,
    BY_SELECT,
    ORDER_SELECT,
    TEMPERAMENTS_SELECT,
    NAME_SEARCH,
    PAGE_NUMBER,
    AMOUNT_PAGES,
    LOADING,
    SEARCH_ID,
    CLEAR_DETAIL_DOGS
}